name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
          cd src
          	xcodebuild clean test -project swift-petitparser.xcodeproj -scheme swift-petitparser CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
